name: test python app
on:
    push
jobs:
    run-app:
        name: run python
        runs-on: ubuntu-latest
        steps:
          - name: code checkout
            uses: actions/checkout@v3

          - name: download gcc
            run: sudo apt install build-essential
            # run: apt-get add --no-cache gcc musl-dev linux-headers
        
          - name: install dependencies
            run: pip install -r requirements.txt

          - name: run your app
            run: flask run

          - name: get output printed
            run: curl http://localhost:5000
            
            