name: test python app
on:
    push
jobs:
    run-app:
        name: run python
        runs-on: ubuntu:20.04
        steps:
          - name: code checkout
            uses: actions/checkout@v3

          - name: build the image
            run: docker-compose up -d

          - name: check server response
            run: curl http://localhost:9000
