name: test python app
on:
    push
jobs:
    run-app:
        name: run python
        runs-on: ubuntu-latest
        steps:
          - name: code checkout
            uses: actions/checkout@v3

          - name: build the image
            uses: actions/setup-buildx-action@v2

          - name: build the image
            uses: docker/build-push-action@v3
            with:
              tags: taghridteetee/pyapp
          
          - name: create container
            run: docker run -d taghridteetee/pyapp

          - name: get output printed
            run: curl http://localhost:5000
            
            