name: test python app
on:
    push
jobs:
    run-app:
        name: run python
        runs-on: ubuntu-latest
        steps:
          - name: code checkout
            uses: actions/checkout@v3

          # - name: build the image
          #   uses: docker/setup-buildx-action@v2

          - name: build the image
            run: docker build -t simplex .

          - name: run redis
            run: docker run -d -it redis:alpine
          
          - name: create container
            run: docker run -d simplex

          - name: get output printed
            run: curl http://localhost:5000
            
            